//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusBookClient.CampusBook_PatronService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CampusBook_PatronService.IPatronService")]
    public interface IPatronService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/GetPatronByUsername", ReplyAction="http://tempuri.org/IPatronService/GetPatronByUsernameResponse")]
        CampusBookService.Patron GetPatronByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/GetPatronByUsername", ReplyAction="http://tempuri.org/IPatronService/GetPatronByUsernameResponse")]
        System.Threading.Tasks.Task<CampusBookService.Patron> GetPatronByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/SignupPatron", ReplyAction="http://tempuri.org/IPatronService/SignupPatronResponse")]
        CampusBookService.Patron SignupPatron(CampusBookService.Patron pt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/SignupPatron", ReplyAction="http://tempuri.org/IPatronService/SignupPatronResponse")]
        System.Threading.Tasks.Task<CampusBookService.Patron> SignupPatronAsync(CampusBookService.Patron pt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/GetValidBranches", ReplyAction="http://tempuri.org/IPatronService/GetValidBranchesResponse")]
        string[] GetValidBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/GetValidBranches", ReplyAction="http://tempuri.org/IPatronService/GetValidBranchesResponse")]
        System.Threading.Tasks.Task<string[]> GetValidBranchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/LoginPatron", ReplyAction="http://tempuri.org/IPatronService/LoginPatronResponse")]
        CampusBookService.Patron LoginPatron(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/LoginPatron", ReplyAction="http://tempuri.org/IPatronService/LoginPatronResponse")]
        System.Threading.Tasks.Task<CampusBookService.Patron> LoginPatronAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/LogoutPatron", ReplyAction="http://tempuri.org/IPatronService/LogoutPatronResponse")]
        bool LogoutPatron(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/LogoutPatron", ReplyAction="http://tempuri.org/IPatronService/LogoutPatronResponse")]
        System.Threading.Tasks.Task<bool> LogoutPatronAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/GetPatronsFullNameByUsername", ReplyAction="http://tempuri.org/IPatronService/GetPatronsFullNameByUsernameResponse")]
        System.Data.DataSet GetPatronsFullNameByUsername(string[] usernames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatronService/GetPatronsFullNameByUsername", ReplyAction="http://tempuri.org/IPatronService/GetPatronsFullNameByUsernameResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPatronsFullNameByUsernameAsync(string[] usernames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPatronServiceChannel : CampusBookClient.CampusBook_PatronService.IPatronService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatronServiceClient : System.ServiceModel.ClientBase<CampusBookClient.CampusBook_PatronService.IPatronService>, CampusBookClient.CampusBook_PatronService.IPatronService {
        
        public PatronServiceClient() {
        }
        
        public PatronServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatronServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatronServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatronServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CampusBookService.Patron GetPatronByUsername(string username) {
            return base.Channel.GetPatronByUsername(username);
        }
        
        public System.Threading.Tasks.Task<CampusBookService.Patron> GetPatronByUsernameAsync(string username) {
            return base.Channel.GetPatronByUsernameAsync(username);
        }
        
        public CampusBookService.Patron SignupPatron(CampusBookService.Patron pt) {
            return base.Channel.SignupPatron(pt);
        }
        
        public System.Threading.Tasks.Task<CampusBookService.Patron> SignupPatronAsync(CampusBookService.Patron pt) {
            return base.Channel.SignupPatronAsync(pt);
        }
        
        public string[] GetValidBranches() {
            return base.Channel.GetValidBranches();
        }
        
        public System.Threading.Tasks.Task<string[]> GetValidBranchesAsync() {
            return base.Channel.GetValidBranchesAsync();
        }
        
        public CampusBookService.Patron LoginPatron(string username, string password) {
            return base.Channel.LoginPatron(username, password);
        }
        
        public System.Threading.Tasks.Task<CampusBookService.Patron> LoginPatronAsync(string username, string password) {
            return base.Channel.LoginPatronAsync(username, password);
        }
        
        public bool LogoutPatron(string username) {
            return base.Channel.LogoutPatron(username);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutPatronAsync(string username) {
            return base.Channel.LogoutPatronAsync(username);
        }
        
        public System.Data.DataSet GetPatronsFullNameByUsername(string[] usernames) {
            return base.Channel.GetPatronsFullNameByUsername(usernames);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPatronsFullNameByUsernameAsync(string[] usernames) {
            return base.Channel.GetPatronsFullNameByUsernameAsync(usernames);
        }
    }
}
